#LeeesVelocityQueue Version: 1.2.0 RELEASE
queue-server: "queue"
main-server: "8b8t"
main-server-slots: 400
always-queue: true #When true, players will always be queued even when the main server is not full
queue-grace-ms: 3000 #Delay in milliseconds before a player is sent from the queue server to the main server
messages:
  interval: 10 #In seconds
  server-full: "&r&68b8t is full"
  commands-blocked: "&cYou cannot use commands while in the queue"
  server-switch-blocked: "&cYou can only be on the queue server while in the queue"
  queue-position: "&6Position in queue: &l%d"
  queue-end: "&6Connecting to 8b8t..."
#this shows the queue size when you hover over the ping on the server list
custom-query:
  enable: false
  query:
    - "&98b&78t &8Queue Info"
    - "&8Priority: &l%priority%"
    - "&8Regular: &l%regular%"
    - "&8Total in queue: &l%totalinqueue%"
    - "&8Max players on main server: &l%maxplayers%"
    - "&8Get a rank to receive priority queue at &chttps://shop.8b8t.me"
  #Leave empty to disable and use the server's actual version
  protocol-message: ""
  #-1 for +1 mode i.e 30/31 online, leave empty to disable and use the server's actual max players
  max-players:
tablist:
  header:
    - ""
    - "&98builders&78tools"
    - ""
    - "&68b8t is full"
    - "Position in queue: &l%position%"
    - "&r&6Estimated time: &l%wait%"
    - ""
  priority-queue-footer:
    - ""
    - "&6You have priority queue status please wait for an available slot on the server"
    - ""
    - "&7Contact: contact@8b8t.me"
    - "&7Discussion: http://discord.8b8t.me"
    - "&7Website: https://www.8b8t.me"
    - "&7These are the only official 8b8t websites and contacts"
    - ""
  normal-queue-footer:
    - ""
    - "&6You can now shop to receive priority queue status, please visit shop.8b8t.me"
    - ""
    - "&7Contact: contact@8b8t.me"
    - "&7Discussion: http://discord.8b8t.me"
    - "&7Website: https://www.8b8t.me"
    - "&7These are the only official 8b8t websites and contacts"
    - ""